qs = {"What does \"advantage\" mean in 5.5e?", 
        "Can you explain disadvantage simply?",
        "What counts as a \"creature\"?",
        "What is considered an \"object\" in the rules?",
        "What does \"visible\" mean in gameplay terms?",
        "What is \"line of sight\" exactly?",
        "Define \"cover\" in D&D.",
        "What does \"half cover\" do mechanically?",
        "What is \"total cover\"?",
        "What does \"difficult terrain\" do?",
        "What counts as magical damage?",
        "What is a \"condition\"?",
        "What does \"temporary hit points\" mean?",
        "What is \"initiative\"?",
        "What counts as an \"attack roll\"?",
        "What is a \"saving throw\"?",
        "What’s the difference between ability checks and saving throws?",
        "What’s the difference between advantage and a bonus?",
        "Is disadvantage the same as a penalty?",
        "Does cover stack with disadvantage?",
        "What’s the difference between concealment and cover?",
        "Is a spell attack an attack roll?",
        "Are saving throws affected by advantage?",
        "What’s the difference between prone and restrained?",
        "Does difficult terrain stack with other movement penalties?",
        "Is magical damage different from spell damage?",
        "What’s the difference between concentration and duration?",
        "If I can’t see a creature but know where it is, do I have disadvantage?",
        "Can I target something behind total cover?",
        "Does invisible mean undetectable?",
        "Can you attack something you can’t see?",
        "Does advantage cancel disadvantage always?",
        "If I have multiple sources of advantage, do they stack?",
        "If I have both advantage and disadvantage, what happens?",
        "Can an object make a saving throw?",
        "Do unconscious creatures automatically fail saves?",
        "Can you willingly fail a saving throw?",
        "What happens if two effects change movement speed differently?",
        "Does being prone affect ranged attacks against you?",
        "If I’m behind a wall but leaning out, do I have cover?",
        "If an enemy is in darkness and I have darkvision, do I still have disadvantage?",
        "If I’m restrained, can I still cast spells?",
        "If I fall prone, does it cost movement to stand up?",
        "If I move through difficult terrain while slowed, how is movement calculated?",
        "If I’m invisible but making noise, can I be targeted?",
        "If I ready an action, how does initiative interact?",
        "If I’m concentrating and take damage, what happens exactly?",
        "If two creatures occupy similar space (like grappling), how does targeting work?",
        "Explain advantage like I’m new to D&D.",
        "When do I roll with disadvantage?",
        "How do I know if I have cover?",
        "What situations give advantage?",
        "What situations give disadvantage?",
        "How does movement work in combat?",
        "What counts as an action vs bonus action?",
        "When do I roll initiative?",
        "How do saving throws work in practice?",
        "What does \"within range\" mean exactly?",
        "What does Fireball do?",
        "How does Magic Missile work?",
        "What is the range of Cure Wounds?",
        "What does Shield do?",
        "How long does Invisibility last?",
        "What is the damage of Lightning Bolt?",
        "What does Detect Magic detect?",
        "How does Mage Armor work?",
        "What is the casting time of Misty Step?",
        "What does Counterspell do?",
        "Does Fireball require line of sight?",
        "Can Magic Missile miss?",
        "Does Shield work after I know I’m hit?",
        "Can I cast spells while invisible?",
        "Does Invisibility break when attacking?",
        "Can I concentrate on two spells at once?",
        "What happens if concentration is broken?",
        "Do spells go through walls?",
        "Can spells crit?",
        "Do spell attacks use proficiency?",
        "Can Counterspell stop Counterspell?",
        "Does Dispel Magic remove all effects?",
        "Can you stack multiple buffs from spells?",
        "Does Haste stack with other speed effects?",
        "Can Shield block Magic Missile?",
        "Does Invisibility give advantage on attacks?",
        "Can Detect Magic see invisible creatures?",
        "Does Silence stop all spellcasting?",
        "Can you cast a spell inside an Antimagic Field?",
        "Do ongoing spells persist after the caster dies?",
        "What happens if Fireball is cast in a small room?",
        "Can I target a point I can’t see with a spell?",
        "Can I cast a spell through a familiar?",
        "Can spells affect objects?",
        "Can I willingly fail a spell save?",
        "What happens if a spell’s target disappears mid-cast?",
        "Can I hold a spell and release it later?",
        "What happens if Counterspell fails?",
        "Can a spell affect something behind total cover?",
        "Does casting a spell break stealth?",
        "If I cast Fireball into darkness, what happens?",
        "If I’m invisible and cast a spell, do I stay invisible?",
        "If I Counterspell a spell, does the slot get wasted?",
        "If two casters Counterspell each other, what happens?",
        "If I’m silenced, can I cast non-verbal spells?",
        "If I’m grappled, can I still cast spells?",
        "If I teleport with Misty Step, do I provoke opportunity attacks?",
        "If I cast Fly and lose concentration mid-air, what happens?",
        "If I cast Shield multiple times, does it stack?",
        "If I cast a spell as a reaction, can I still cast another spell?",
        "Can I cast Fireball and then Misty Step in the same turn?",
        "If I’m concentrating on Invisibility and take damage, how do I roll?",
        "can i cast fireball through a wall?",
        "does invis break if i attack",
        "can u counterspell counterspell lol",
        "what happens if i lose concentration mid spell",
        "can magic missile miss or nah",
        "do spells crit in 5.5",
        "can i stack shield spell multiple times",
        "if im invisible can enemies still hit me",
        "how does detect magic actually work",
        "can i cast 2 spells same turn",
        "what happens if fireball in tiny room",
        "can spells go through doors",
        "does silence stop all magic",
        "can i cast while grappled",
        "do i need to see target for spellsCan I Counterspell a spell cast with Subtle Spell?",
        "If I cast Haste and then lose concentration, what exactly happens?",
        "Can I cast a bonus action spell and a reaction spell in the same round?",
        "If I ready a spell, do I need concentration?",
        "Can I cast spells while restrained or prone?",
        "How does casting a spell interact with opportunity attacks?",
        "Can I cast a spell while falling?",
        "If I multiclass, how do spell slots work?",
        "What does the glossary say about advantage?",
        "According to the rules, how does concentration work?",
        "What is the official definition of cover?",
        "What does the spell description of Fireball say about damage?",
        "What are the exact effects of the Shield spell?",
        "What conditions break Invisibility according to the spell?",
        "What does the rules glossary say about attack rolls?",
        "What are the components of Counterspell?",
        "What is the exact wording for Magic Missile targeting?",
        "What does the glossary define as difficult terrain?",
        "Can I do this with advantage?",
        "Does this spell work here?",
        "Can I target that?",
        "Do I get disadvantage?",
        "Does it stack?",
        "Can I still cast?",
        "What happens if I fail?",
        "Does this break concentration?",
        "Can I react to that?",
        "Is that allowed?",
        "What does advantage mean in 5.5e?",
        "what does advantage mean in 5.5e",
        "What does \"advantage\" mean",
        "define advantage dnd 5.5",
        "advantage meaning in dnd",
        "how does advantage work",
        "how does advantage work in 5.5e?",
        "explain advantage simply",
        "explain advantage like im new",
        "advantage rules explain",
        "what is advantage mechanic",
        "how advantage works exactly",
        "what does advantage actually do",
        "what happens when you have advantage",
        "advantage vs normal roll whats different",
        "advantage roll how many dice",
        "advantage means roll twice right",
        "is advantage just roll 2 dice",
        "advantage explanation please",
        "what is advantage in gameplay terms",
        "Can you explain disadvantage simply?",
        "explain disadvantage",
        "what is disadvantage",
        "disadvantage meaning",
        "how does disadvantage work",
        "how disadvantage works in dnd",
        "disadvantage rules explain",
        "explain disadvantage like im new",
        "what does disadvantage actually do",
        "when do you get disadvantage",
        "disadvantage roll how many dice",
        "disadvantage vs penalty",
        "is disadvantage same as penalty",
        "disadvantage means roll twice lowest right",
        "what happens when i have disadvantage",
        "how do i apply disadvantage",
        "disadvantage mechanic explain",
        "simple explanation disadvantage",
        "What counts as a creature?",
        "what counts as a creature in dnd",
        "define creature rules",
        "what is considered a creature",
        "what qualifies as a creature",
        "creature definition rules glossary",
        "is a summoned thing a creature",
        "are monsters creatures",
        "what is not a creature",
        "what counts as creature vs object",
        "What is considered an object in the rules?",
        "what counts as object dnd",
        "define object rules",
        "object meaning in dnd",
        "what qualifies as object",
        "object vs creature difference",
        "is a weapon an object",
        "is armor an object",
        "what is an object exactly",
        "object rules explanation",
        "What does visible mean in gameplay terms?",
        "what does visible mean",
        "define visible dnd",
        "what counts as visible",
        "visible rules explain",
        "when is something considered visible",
        "does visible mean clearly seen",
        "what is visibility in dnd",
        "What is line of sight exactly?",
        "what is line of sight",
        "define line of sight dnd",
        "how line of sight works",
        "line of sight explanation",
        "what blocks line of sight",
        "line of sight rules simple",
        "do walls block line of sight",
        "line of sight vs range",
        "what counts as line of sight",
        "Define cover in D&D.",
        "what is cover dnd",
        "cover meaning",
        "how cover works",
        "explain cover simply",
        "cover rules explanation",
        "what counts as cover",
        "cover mechanic explain",
        "how do i know if i have cover",
        "cover system dnd",
        "What does half cover do mechanically?",
        "what is half cover",
        "half cover bonus what is it",
        "half cover effect",
        "explain half cover",
        "how half cover works",
        "half cover rules dnd",
        "what does half cover give you",
        "half cover numbers",
        "What is total cover?",
        "total cover meaning",
        "define total cover",
        "what does total cover do",
        "total cover rules explain",
        "can you target through total cover",
        "total cover explanation",
        "what counts as total cover",
        "What does difficult terrain do?",
        "difficult terrain meaning",
        "how difficult terrain works",
        "define difficult terrain",
        "what happens in difficult terrain",
        "difficult terrain rules explain",
        "does difficult terrain halve movement",
        "difficult terrain explanation simple",
        "movement in difficult terrain",
        "What counts as magical damage?",
        "what is magical damage",
        "define magical damage",
        "magical damage vs normal damage",
        "what qualifies as magical damage",
        "is spell damage magical damage",
        "magical damage rules",
        "What is a condition?",
        "define condition dnd",
        "what are conditions",
        "condition meaning",
        "explain conditions simply",
        "what counts as a condition",
        "condition system dnd",
        "What does temporary hit points mean?",
        "temp hp meaning",
        "what are temporary hit points",
        "temp hp rules explain",
        "how temp hp works",
        "do temp hp stack",
        "temporary hp explanation",
        "What is initiative?",
        "initiative meaning",
        "how initiative works",
        "define initiative dnd",
        "when do you roll initiative",
        "initiative rules simple",
        "initiative order explain",
        "What counts as an attack roll?",
        "attack roll meaning",
        "define attack roll",
        "what is an attack roll exactly",
        "spell attack is attack roll?",
        "attack roll rules explain",
        "What is a saving throw?",
        "saving throw meaning",
        "define saving throw",
        "what is saving throw exactly",
        "how saving throws work",
        "saving throw explanation",
        "difference between ability check and saving throw",
        "ability check vs saving throw",
        "saving throw vs check difference",
        "what’s diff ability vs save",
        "checks vs saves explain",
        "advantage vs bonus difference",
        "is advantage same as bonus",
        "advantage vs modifier",
        "does advantage add numbers",
        "bonus vs advantage explain",
        "is disadvantage same as penalty",
        "disadvantage vs penalty difference",
        "are penalties same as disadvantage",
        "penalty vs disadvantage",
        "if i cant see a creature but know location do i have disadvantage",
        "cant see target but know where it is disadvantage?",
        "unseen target but known location disadvantage or not",
        "if target invisible but i know position what happens",
        "attacking unseen target rules",
        "can i target something behind total cover",
        "target behind total cover allowed?",
        "can spells hit through total cover",
        "can i attack through full cover",
        "total cover targeting rules",
        "does invisible mean undetectable",
        "invisibility = undetectable?",
        "does invis mean cant be found",
        "invisible but still detectable?",
        "can you attack something you cant see",
        "attack unseen target allowed",
        "can i hit something invisible",
        "attacking without sight rules",
        "does advantage cancel disadvantage always",
        "advantage + disadvantage what happens",
       " do they cancel each other",
        "adv and disadv interaction",
        "both advantage and disadvantage result?",
        "what does fireball do",
        "fireball spell explain",
        "fireball effect",
        "how fireball works",
        "fireball damage and range",
        "explain fireball simply",
        "how does magic missile work",
        "magic missile explain",
        "magic missile rules",
        "does magic missile auto hit",
        "magic missile behavior",
        "what does shield do",
        "shield spell explain",
        "shield reaction how works",
        "shield bonus amount",
        "shield timing rules",
        "how long does invisibility last",
        "invisibility duration",
        "invis spell duration",
        "how long invis stays active",
        "does fireball require line of sight",
        "fireball need LOS?",
        "can i cast fireball without seeing target",
        "fireball targeting rules",
        "can magic missile miss",
        "magic missile miss or no",
        "does magic missile auto hit always",
        "can you dodge magic missile",
        "can i cast spells while invisible",
        "casting spells while invis allowed",
        "invis + casting interaction",
        "does invisibility break when attacking",
        "invis breaks on attack?",
        "attacking while invisible what happens",
        "can i concentrate on two spells",
        "2 concentration spells allowed?",
        "multiple concentration spells",
        "stacking concentration",
        "do spells go through walls",
        "can spells pass through walls",
        "spell through wall allowed?",
        "wall blocking spells rules",
        "can i cast fireball through wall",
        "can i cast fireball thru a wall?",
        "fireball through wall yes or no",
        "can u fireball behind wall",
        "fireball go through walls???",
        "does invis break if i attack",
        "invis break on attack",
        "if i attack do i lose invis",
        "attacking while invis break it?",
        "can u counterspell counterspell lol",
        "counterspell vs counterspell what happens",
        "can counterspell counter another counterspell",
        "counterspell chain interaction",
        "what happens if i lose concentration mid spell",
        "lose concentration mid spell what happens",
        "concentration breaks then what",
        "if concentration fails result?",
        "can magic missile miss or nah",
        "magic missile miss or nah lol",
        "can magic missile fail",
        "magic missile always hit?",
        "can i cast 2 spells same turn",
        "cast two spells same turn allowed",
        "2 spells per turn rules",
        "can i double cast",
        "what does the glossary say about advantage",
        "advantage definition official",
        "rules glossary advantage wording",
        "official advantage definition",
        "what is official definition of cover",
        "cover rules exact wording",
        "cover glossary definition",
        "what does fireball description say about damage",
        "fireball exact wording damage",
        "spell text fireball damage",
        "advantage?",
        "disadvantage?",
        "cover?",
        "invis?",
        "fireball?",
        "concentration?",
        "can i cast?",
        "does it stack?",
        "allowed?",
        "works?",
        "how exactly does advantage change the roll",
        "advantage roll explain like simple terms",
        "what do i roll when i have advantage again",
        "advantage means take highest right",
        "roll with advantage example please",
        "can you explain advantage with example",
        "advantage mechanic detailed explanation",
        "how advantage affects probability",
        "advantage effect on dice rolls",
        "what happens mechanically with advantage",
        "advantage rule wording exact",
        "glossary definition advantage please",
        "advantage roll two d20 or something else",
        "advantage only applies to d20?",
        "advantage apply to damage rolls?",
        "advantage on saving throws possible?",
        "can advantage apply to skill checks",
        "when exactly do you gain advantage",
        "how do i know if advantage applies",
        "advantage stacking yes or no",
        "multiple advantage sources what happens",
        "advantage twice means what",
        "advantage vs double roll difference",
        "advantage interaction with rerolls",
        "advantage and lucky feat interaction",
        "how exactly does disadvantage work in detail",
        "disadvantage means lowest roll right",
        "roll 2 dice disadvantage pick lowest?",
        "disadvantage rule wording",
        "disadvantage interaction with rerolls",
        "disadvantage on saving throws possible",
        "can disadvantage apply to attack rolls only?",
        "disadvantage example scenario",
        "how disadvantage affects probability",
        "disadvantage edge cases explain",
        "when do i get disadvantage exactly",
        "disadvantage stacking rules",
        "multiple disadvantage sources what happens",
        "disadvantage twice means what",
        "disadvantage vs penalty numbers",
        "disadvantage vs -2 penalty difference",
        "disadvantage and advantage together example",
        "is a familiar a creature or object",
        "are illusions creatures",
        "is undead considered creature",
        "is a corpse a creature",
        "when does a creature become an object",
        "creature definition edge cases",
        "is a summoned weapon a creature",
        "are constructs creatures",
        "what counts as living creature",
        "does creature include players and monsters",
        "is a door an object",
        "is a magical barrier an object",
        "can objects take damage",
        "object hp rules",
        "object saving throws allowed?",
        "can objects be targeted by spells",
        "object vs structure difference",
        "what defines an object exactly",
        "are vehicles objects",
        "if i can hear but not see target what happens",
        "hearing vs seeing for targeting rules",
        "partial visibility rules",
        "dim light visibility effects",
        "darkness visibility rules",
        "does darkvision count as seeing normally",
        "invisible but outlined does it count visible",
        "if blinded can i still target enemies",
        "line of sight vs line of effect difference",
        "what blocks line of effect vs line of sight",
        "does fog block line of sight",
        "does glass block line of sight",
        "line of sight through illusion?",
        "can you see through magical darkness",
        "cover from multiple directions how works",
        "can allies provide cover",
        "does enemy count as cover",
        "cover while prone interaction",
        "cover while moving",
        "partial cover vs half cover difference",
        "stacking cover sources possible?",
        "can you ignore cover somehow",
        "spells ignore cover?",
        "ranged attacks and cover interaction",
        "does cover apply to spells",
        "cover vs aoe spells interaction",
        "difficult terrain and flying interaction",
        "does difficult terrain affect flying speed",
        "swimming in difficult terrain?",
        "climbing and difficult terrain stack?",
        "movement penalties stacking rules",
        "speed reduced to 0 what happens",
        "multiple speed modifiers interaction",
        "dash action with difficult terrain",
        "movement rounding rules",
        "diagonal movement rules",
        "moving through creatures rules",
        "moving through allies vs enemies",
        "prone condition exact effects",
        "restrained condition details,",
        "grappled vs restrained difference",
        "blinded condition effect on attacks",
        "deafened condition effect",
        "charmed condition rules",
        "frightened condition movement restriction",
        "stunned condition full effects",
        "unconscious condition rules exact",
        "incapacitated vs stunned difference",
        "exhaustion condition stacking",
        "conditions that affect saving throws",
        "initiative ties what happens",
        "reroll initiative possible?",
        "surprise and initiative interaction",
        "when does combat officially start",
        "ready action timing exact",
        "reaction timing rules",
        "bonus action timing rules",
        "can you delay turn",
        "can you hold initiative",
        "initiative order changes mid combat?",
        "attack roll vs damage roll difference",
        "natural 20 on attack roll effect",
        "natural 1 effect attack roll",
        "do saving throws crit",
        "natural 20 on saving throw?",
        "saving throw auto fail on 1?",
        "attack roll modifiers stacking",
        "saving throw modifiers stacking",
        "proficiency applied to saves when",
        "spell save dc calculation",
        "cure wounds healing amount",
        "cure wounds scaling higher level",
        "lightning bolt aoe shape explanation",
        "detect magic duration and range",
        "mage armor ac calculation",
        "misty step teleport restrictions",
        "counterspell range and timing",
        "dispel magic vs counterspell difference",
        "invisibility conditions break",
        "shield duration exact timing",
        "spell components V S M meaning",
        "can i cast without verbal component",
        "somatic component free hand requirement",
        "material components consumed or not",
        "focus replacing material components",
        "ritual casting rules",
        "spell slots vs prepared spells",
        "cantrips scaling rules",
        "upcasting spells effects",
        "spellcasting ability modifier usage",
        "spell attack bonus calculation",
        "saving throw dc formula",
        "haste and slow interaction",
        "fly and grapple interaction",
        "invisibility and blindsight interaction",
        "detect magic and illusion interaction",
        "silence and subtle spell interaction",
        "antimagic field vs magic items",
        "concentration spells stacking buffs",
        "ongoing damage spells stacking",
        "area spells overlapping effects",
        "reaction spells timing conflicts",
        "if im prone and someone shoots me do they get advantage",
        "if im restrained can i still dodge",
        "if im blinded and attack do i have disadvantage",
        "if enemy is invisible and prone what happens",
        "if im in darkness and enemy has darkvision do they get advantage",
        "if i cast fireball behind cover does cover apply",
        "if im flying and knocked prone do i fall instantly",
        "if im concentrating and get hit multiple times do i roll multiple saves",
        "if i ready a spell and dont use it what happens",
        "if i teleport into occupied space what happens",
        "if i cast spell and target moves out of range mid cast",
        "if i cast spell and lose line of sight mid cast",
        "if i counterspell a reaction spell timing?",
        "if i cast shield after knowing roll but before damage?",
        "can i cast fireball and move in same turn and also bonus action?",
        "if i have advantage and disadvantage and cover what applies first",
        "can i be invisible and still have disadvantage somehow",
        "if i cast invisibility then attack then hide what happens",
        "if i counterspell and they counterspell my counterspell what happens",
        "if i lose concentration and regain it can spell continue",
        "can i stack mage armor and shield and cover",
        "if im prone behind cover and invisible what bonuses apply",
        "can i like cast fireball behind a wall or nah",
        "so like invisibility if i attack it breaks right???",
        "wait does advantage stack or no",
        "ok but what if i have like 2 advantage sources",
        "can u like counterspell someone counterspelling you lol",
        "if im blinded can i still hit stuff??",
        "do i roll twice for advantage or what",
        "is disadvantage just minus something??",
        "can spells go thru walls or not",
        "does cover even matter for spells??",
        "can i just target like anywhere with fireball",
        "what happens if concentration just drops randomly",
        "can i hold spell and use later or no",
        "can i cast 2 spells same turn if one is bonus",
        "is invis broken by like any action or just attack",
        "can enemies still find me if im invis",
        "magic missile always hits right?? like always??",
        "can u miss with magic missile ever",
        "can i cast while tied up",
        "what if im grappled and want to cast",
        "does silence stop ALL spells or just some",
        "can i still cast without talking",
        "whats the deal with somatic components",
        "do i need free hand to cast",
        "advantage how",
        "disadvantage when",
        "cover rules?",
        "invis break?",
        "spell stack?",
        "can cast?",
        "concentration??",
        "fireball wall?",
        "magic missile miss?",
        "shield timing?",
        "advantage how does it actually modify the roll",
        "advantage means roll twice and pick best correct",
        "do you always roll 2 d20 for advantage",
        "advantage applies before modifiers or after",
        "advantage changes probability how exactly",
        "advantage affects crit chance?",
        "advantage increases odds of nat 20 right",
        "how advantage interacts with critical hits",
        "advantage on attack vs saving throw difference",
        "advantage on skill checks possible?",
        "can advantage apply to initiative rolls",
        "initiative with advantage allowed?",
        "advantage granted by spells examples",
        "advantage from conditions list?",
        "advantage from invisibility confirmed?",
        "advantage from prone vs ranged?",
        "advantage rules exact text please",
        "official advantage glossary wording",
        "advantage stacking multiple times allowed or no",
        "advantage from multiple sources wasted?",
        "advantage replaced if already have it?",
        "advantage with reroll mechanics interaction",
        "advantage + inspiration interaction",
        "does advantage change if i have this ability \"You gain the following benefits. Luck Points. You have a number of Luck Points equal to your Proficiency Bonus and can spend the points on the benefits below. You regain your expended Luck Points when you finish a Long Rest. Advantage. When you roll a d20 for a D20 Test, you can spend 1 Luck Point to give yourself Advantage on the roll. Disadvantage. When a creature rolls a d20 for an attack roll against you, you can spend 1 Luck Point to impose Disadvantage on that roll.\"",
        "disadvantage exact math behind it",
        "disadvantage lowers chance of crit right",
        "disadvantage roll pick lowest confirm",
        "disadvantage interaction with nat 1s",
        "disadvantage and crit fail chance",
        "disadvantage applied before modifiers?",
        "disadvantage from conditions list",
        "disadvantage from blinded condition",
        "disadvantage from prone melee vs ranged",
        "disadvantage stacking clarification",
        "disadvantage from multiple sources wasted?",
        "disadvantage and advantage cancel always?",
        "disadvantage + advantage + another advantage result?",
        "disadvantage interaction with rerolls",
        "is a dead body still a creature or object",
        "when creature dies does it become object immediately",
        "corpse classification rules",
        "is summoned spirit a creature",
        "illusion creatures count as creatures?",
        "are constructs considered creatures always",
        "is animated armor creature or object",
        "what about familiars creature classification",
        "mounts creature classification",
        "are players considered creatures rules-wise",
        "creature definition includes NPCs?",
        "does creature include self",
        "is a wall an object or structure",
        "is a building an object",
        "object size categories exist?",
        "object hp and ac rules",
        "can objects be crit",
        "do objects have saving throws ever",
        "can objects fail dex saves",
        "targeting objects with spells rules",
        "are magic items objects or separate category",
        "object vs environment difference",
        "if i hear enemy but cant see do i attack disadvantage",
        "hearing replaces sight for targeting?",
        "blind fighting removes disadvantage?",
        "invisibility but footprints visible?",
        "partial invisibility case?",
        "see invisible vs invisibility interaction",
        "blindsight vs invisibility rules",
        "tremorsense vs visibility rules",
        "does fog cloud block vision fully",
        "heavy obscurement vs light obscurement difference",
        "darkness vs magical darkness difference",
        "can you see through darkness with darkvision fully?",
        "does dim light impose disadvantage",
        "is visibility binary or partial",
        "ally standing in front gives cover?",
        "enemy between me and target gives cover?",
        "multiple creatures between me and target stacking cover?",
        "cover from corners calculation",
        "leaning out of cover rules",
        "peeking gives cover still?",
        "can you shoot and return to cover same turn",
        "cover during movement",
        "does cover apply to saving throws",
        "dex saves and cover interaction",
        "fireball and cover interaction exact",
        "cover vs aoe spells partial effect",
        "ignoring cover abilities examples",
        "speed reduced by half twice equals what",
        "stacking slow effects calculation",
        "movement rounding up or down",
        "grid vs theater of mind movement difference",
        "moving diagonally cost rules",
        "moving through allies cost",
        "moving through enemies allowed?",
        "squeezing through spaces rules",
        "difficult terrain + prone interaction",
        "standing up cost exact",
        "standing up uses half speed right",
        "speed reduced to 0 can you still stand",
        "forced movement triggers opportunity attacks?",
        "teleport counts as movement?",
        "prone + restrained combined effects",
        "blinded + invisible interaction",
        "grappled + restrained difference exact",
        "frightened movement limitation exact wording",
        "charmed prevents attacks fully?",
        "stunned vs incapacitated difference",
        "unconscious auto crit rules",
        "unconscious saving throw rules",
        "death saving throws conditions",
        "exhaustion level effects breakdown",
        "stacking conditions interaction rules",
        "action vs bonus action vs reaction timing exact",
        "can i take reaction on my own turn",
        "can multiple reactions happen in round",
        "ready action uses reaction right",
        "ready action spell concentration requirement",
        "bonus action spell restriction rule exact",
        "casting bonus spell prevents action spell?",
        "cantrip exception bonus spell rule?",
        "opportunity attack timing exact moment",
        "interrupting movement with reaction",
        "simultaneous effects resolution order",
        "attack roll formula exact",
        "proficiency applied when attacking",
        "ability mod for attack rolls rules",
        "ranged vs melee attack roll difference",
        "spell attack vs weapon attack difference",
        "saving throw dc calculation formula",
        "saving throw proficiency application",
        "partial success on saves exist?",
        "half damage on success rules",
        "evasion interaction with saves",
        "auto fail conditions on saves",
        "can you choose to fail save",
        "casting time types list",
        "reaction casting timing window",
        "casting time longer than 1 action rules",
        "concentration rules exact text",
        "concentration saving throw formula",
        "damage triggers concentration save each hit?",
        "spell ends when concentration lost immediately?",
        "maintaining concentration while incapacitated?",
        "casting while concentrating allowed?",
        "concentration + ready action interaction",
        "concentration while unconscious possible?",
        "verbal component silence interaction",
        "somatic component restrained interaction",
        "somatic requires free hand always?",
        "material component consumed vs reusable",
        "focus replaces material rules",
        "costly material requirements strict?",
        "component pouch vs focus difference",
        "casting without components possible?",
        "subtle spell removing components interaction",
        "fireball radius exact measurement",
        "fireball area shape exact",
        "fireball around corners?",
        "fireball behind wall partial cover?",
        "fireball ignites objects?",
        "fireball damage scaling higher slots",
        "fireball save type dex correct?",
        "fireball half damage on save correct?",
        "fireball centered point rules",
        "fireball indoors effect",
        "magic missile number of darts scaling",
        "magic missile all hit same target allowed?",
        "magic missile split targets allowed?",
        "magic missile damage per dart",
        "magic missile interaction with shield",
        "magic missile auto hit no roll confirm",
        "magic missile targeting requirements",
        "shield adds +5 ac until when exactly",
        "shield works after seeing roll?",
        "shield vs magic missile interaction exact",
        "shield reaction timing window",
        "shield stacking with armor",
        "invisibility ends on attack only?",
        "invisibility ends on spell cast?",
        "invisibility and concentration interaction",
        "invisibility advantage rules exact",
        "invisibility detection methods",
        "invisibility vs blindsight",
        "invisibility vs tremorsense",
        "counterspell range exact",
        "counterspell level interaction",
        "counterspell higher level auto success?",
        "counterspell ability check formula",
        "counterspell reaction timing",
        "counterspell vs subtle spell",
        "counterspell chain resolution",
        "if im invisible and have advantage and target is prone what applies",
        "if i cast fireball and target has cover and evasion what happens",
        "if i counterspell a spell and they counterspell mine and someone else counterspell that what happens",
        "if im blinded but target is restrained do i still have disadvantage",
        "if i have advantage and disadvantage and reroll ability what is final roll",
        "if im concentrating and take damage from multiple sources how many saves",
        "if i cast invisibility then attack then hide again what is state",
        "if i cast shield and have cover and disadvantage what applies first",
        "ok so like if i have advantage but also disadvantage what happens exactly lol",
        "wait do they cancel or something???",
        "can i like cast while invisible and not lose it or nah",
        "does magic missile EVER miss or like no",
        "bro can u counterspell a counterspell or is that illegal",
        "if i cast fireball in a small room do we all just die lol",
        "can i stack shield like multiple times or nah",
        "do spells go thru walls or is that not allowed",
        "if i cant see them but know where they are can i still hit",
        "invisibility kinda broken or am i wrong",
        "can i cast 2 spells same turn if one is bonus idk",
        "what even counts as an object lol",
        "is a dead body still creature???",
        "if im prone do ranged attacks get advantage or disadvantage",
        "can i just choose to fail a saving throw",
        "does silence just completely shut down magic??",
        "advantage rules 5.5",
        "disadvantage explanation simple",
        "cover mechanics dnd",
        "invisibility break conditions",
        "fireball damage rules",
        "magic missile miss question",
        "concentration rules damage",
        "counterspell interaction rules",
        "saving throw definition glossary",
        "attack roll meaning dnd",
        "how does detect magic actually function",
        "detect magic what exactly does it detect",
        "does detect magic see invisible creatures",
        "detect magic vs invisibility interaction",
        "detect magic through walls allowed?",
        "can detect magic see magic items behind cover",
        "detect magic duration and range please",
        "detect magic concentration required?",
        "what schools does detect magic reveal",
        "detect magic aura strength meaning",
        "does detect magic detect ongoing spells",
        "detect magic while blinded?",
        "detect magic in darkness how works",
        "detect magic vs illusion spells",
        "detect magic can it detect curses",
        "what does identify spell do exactly",
        "identify spell reveal curses?",
        "does identify tell all properties",
        "identify casting time and ritual",
        "identify requires touch right?",
        "identify vs detect magic difference",
        "can identify fail",
        "identify on magical traps?",
        "identify item without attunement?",
        "does identify reveal hidden effects",
        "mage armor ac formula exactly",
        "does mage armor stack with armor",
        "mage armor duration rules",
        "mage armor vs shield stacking",
        "mage armor on other creatures allowed",
        "mage armor and dex modifier interaction",
        "mage armor ends when?",
        "mage armor concentration or not",
        "bless adds what exactly",
        "bless affects how many targets",
        "bless duration and concentration",
        "bless stacking possible?",
        "bless on saving throws and attacks?",
        "bless dice size exact",
        "bless multiple casters stacking?",
        "bless interaction with advantage",
        "bane does opposite of bless right",
        "bane penalty exact amount",
        "bane affects saving throws?",
        "bane stacking rules",
        "bane concentration required",
        "bane vs bless interaction",
        "bane effect wording exact",
        "shield of faith ac bonus exact",
        "shield of faith concentration?",
        "shield of faith duration",
        "shield of faith stacking with shield spell",
        "shield of faith on self vs others",
        "scorching ray number of rays",
        "scorching ray attack rolls per ray",
        "scorching ray can target multiple enemies",
        "scorching ray scaling with level",
        "scorching ray damage per ray",
        "scorching ray advantage per ray or all",
        "scorching ray miss some hit some?",
        "scorching ray vs invisibility interaction",
        "chromatic orb damage types list",
        "chromatic orb attack roll or save",
        "chromatic orb range",
        "chromatic orb scaling rules",
        "chromatic orb choosing damage type each cast?",
        "chromatic orb material component cost",
        "chromatic orb vs resistance interaction",
        "burning hands cone size",
        "burning hands save type",
        "burning hands half damage on save",
        "burning hands affects allies?",
        "burning hands vs cover interaction",
        "burning hands indoors what happens",
        "hold person affects only humanoids right",
        "hold person paralysis effect",
        "hold person save type",
        "hold person concentration rules",
        "hold person crit interaction",
        "hold person multiple targets at higher level",
        "hold person vs elves immune?",
        "hold person vs charm immunity",
        "sleep hp pool calculation",
        "sleep affects lowest hp first",
        "sleep ignores saves?",
        "sleep vs undead interaction",
        "sleep vs constructs interaction",
        "sleep duration exact",
        "sleep concentration required?",
        "suggestion limits what can be suggested",
        "suggestion requires understandable language?",
        "suggestion duration",
        "suggestion concentration",
        "suggestion vs charm immunity",
        "suggestion unreasonable commands?",
        "suggestion combat usage",
        "command one word limitation",
        "command duration",
        "command save type",
        "command effect examples",
        "command on multiple targets,"
        "command vs undead works?",
        "command requires understanding language",
        "misty step teleport distance exact",
        "misty step line of sight required?",
        "misty step through walls allowed?",
        "misty step bonus action right",
        "misty step provoke opportunity attacks?",
        "misty step while grappled",
        "misty step while restrained",
        "misty step vertical movement allowed",
        "fly speed granted",
        "fly concentration rules",
        "fly duration",
        "fly losing concentration falling rules",
        "fly while grappled",
        "fly with heavy armor interaction",
        "fly and difficult terrain interaction",
        "levitate movement control",
        "levitate concentration",
        "levitate vertical only?",
        "levitate vs flying difference",
        "levitate on unwilling target save",
        "levitate vs prone interaction",
        "poison spray save type",
        "poison spray range",
        "poison spray damage scaling",
        "poison spray vs poison immunity",
        "poison spray attack roll or save",
        "ray of sickness attack roll",
        "ray of sickness poison effect",
        "ray of sickness save type",
        "ray of sickness damage type",
        "ray of sickness vs poison immunity",
        "hex damage bonus exact",
        "hex concentration rules",
        "hex duration",
        "hex ability disadvantage effect",
        "hex moving target after death",
        "hex stacking possible?",
        "hex vs multiple targets",
        "can i have bless and shield of faith at same time",
        "does hex stack with other damage bonuses",
        "can bane and bless both affect same target",
        "does hold person give advantage automatically",
        "does sleep ignore concentration spells",
        "can i misty step while under suggestion",
        "can i fly while restrained",
        "can i levitate and then cast other spells",
        "does detect magic reveal hex",
        "can identify detect a curse from hex",
        "does bless stack with like advantage or nah",
        "can i hex someone and then hex again lol",
        "hold person means auto crit right??",
        "can sleep just knock out anything??",
        "does suggestion work in combat or no",
        "can i misty step out of grapple or nah",
        "fly spell if i lose it do i just fall??",
        "levitate kinda same as fly or not really",
        "can poison spray miss??",
        "ray of sickness poison always applies??",
        "bane just reverse bless right??",
        "shield of faith and shield stack or no",
        "can i cast detect magic and see invis ppl??",
        "identify tells everything or not",
        "bless spell effect",
        "bane spell rules",
        "hold person rules",
        "sleep spell mechanics",
        "hex spell duration",
        "fly spell rules",
        "levitate spell details",
        "command spell wording",
        "suggestion spell limits",
        "scorching ray rules",
        "does this spell work on that",
        "can i use it like that",
        "will it affect them",
        "does it apply here",
        "can i target that with it",
        "does it break if i do this",
        "can i keep it active",
        "does it stack with others",
        "can i cast it again",
        "is that allowed with this spell",# these next ones are intentionly question that shouldn't be answered
        "who is the strongest god in dnd lore",
        "what is the history of the forgotten realms",
        "who created the weave of magic",
        "what is vecna’s backstory",
        "who are the main villains in dnd",
        "explain the blood war in detail",
        "what is the origin of dragons in dnd",
        "how does my custom class shadow knight work",
        "what does my dm mean by energy corruption mechanic",
        "how does our table rule for crits work",
        "can i use my homebrew spell void collapse",
        "what are the rules for my campaign’s magic system",
        "what is the best class in dnd 5.5",
        "what build does most damage at level 10",
        "how do i optimize my character",
        "what feats should i take for max damage",
        "best multiclass combos",
        "tier list for classes",
        "what is the capital of france",
        "how does gravity work in real life",
        "write me a python script",
        "what is machine learning",
        "explain quantum physics",
        "what is 2 + 2",
        "who won the world cup",
        "can i do that thing we talked about yesterday",
        "does it work like before",
        "can i use it again",
        "what happens in that situation",
        "is that allowed here",
        "can i break the rule if dm says yes",
        "what if something else happens",
        "advantage + lucky feat stacking how works",
        "disadvantage + lucky feat what happens",
        "best dps build level 5",
        "strongest wizard build 5.5",
        "optimal spell list wizard",
        "best feats for sorcerer",
        "multiclass wizard fighter worth it",
        "how should a dm rule this situation",
        "what would a fair ruling be here",
        "is my dm wrong about this rule",
        "can dm override spell rules",
        "what house rules are common",
        "describe a fireball explosion cinematically",
        "write a story about a wizard casting invisibility",
        "create a custom spell stronger than fireball",
        "invent a new condition for dnd",
        "design a boss fight mechanic",
        "compare dnd 5.5 to pathfinder",
        "what changed from 5e to 5.5e",
        "who designed dnd 5.5",
        "what books include these spells",
        "when was fireball first introduced",
        "can i do that combo from earlier",
        "does it still work like last session",
        "can i use that trick again",
        "what happens if i repeat that action",
        "is that interaction still valid",
        "what is the strongest spell in the game",
        "which spell should i pick at level 3",
        "best spell combo for max damage",
        "ranking all spells best to worst",
        "what spell is most fun to use",
        "which spell is overpowered",
        "what spell fits my character theme",
        "can you create a new spell for me",
        "how to homebrew spells balanced"
    }